# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '0 1 * * *'
  watch:
    types: started

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://juejin.cn/user/2999123452110574"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: set git config 
      run: |
        git config --global user.name "Husky-Yellow"
        git config --global user.email "473795376@qq.com"
    - name: git pull erp
      run: |
        git pull
    - name: run srcipt
      run: |
        python 163music.py 341893546 1
    - name: commit to rep
      run: |
        git add README.md
        git commit --allow-empty -m "Update README.md"
        git push

